@cabinsAPI = https://wom-cabins.azurewebsites.net

### Projekt 1 login

POST {{cabinsAPI}}/users/login
Content-Type: application/json

{
    "email": "test",
    "password": "123"
}

### Request till projekt 1/cabins/owned

GET {{cabinsAPI}}/cabins/owned
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM2ZWIyYTliOTkzZTg1M2IxMzdjYTIiLCJlbWFpbCI6InNhbGVAYXJjYWRhIiwiaWF0IjoxNjY1NjY3MzM3LCJleHAiOjE2NjU3NTM3Mzd9.g6H2HVQBPa_QNp4xr4TgnvmIBDpI6QYisoZM1pAPWI0