@baseURL = http://localhost:3031
@cabinsAPI = https://wom-cabins.azurewebsites.net

### hämta alla 
GET {{baseURL}}/orders
Content-Type: application/json



### Skapa en ny
POST {{baseURL}}/orders/634435fad10640621de0226d
Content-Type: application/json

{
   "date": "2022-09-27"
}


###Modifiera beställning

PATCH {{baseURL}}/orders/6344366f95d03bad64c7de6f
Content-Type: application/json

{
    "date": "2022-09-28"
}


### Radera 
DELETE {{baseURL}}/orders/6344366f95d03bad64c7de6f
Content-Type: application/json

### Projekt 1 login

POST {{cabinsAPI}}/users/login
Content-Type: application/json

{
    "email": "sale@arcada",
    "password": "Password123"
}

### Request till projekt 1/cabins/owned

GET {{cabinsAPI}}/cabins/owned
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzM2ZWIyYTliOTkzZTg1M2IxMzdjYTIiLCJlbWFpbCI6InNhbGVAYXJjYWRhIiwiaWF0IjoxNjY1NTcwMjE1LCJleHAiOjE2NjU2NTY2MTV9.-sgoTpfkskNo0OyIg6fDm_D8fewjGcJoiEMAzxU4ylw