@baseURL = http://localhost:3031

### Upload tjänster

POST {{baseURL}}/services/upload
Content-Type: application/json

{
    "name": "Cleaning"
}


### Hämta alla tjänster

GET {{baseURL}}/services
Content-Type: application/json


### Modifiera tjänst

PATCH {{baseURL}}/services/63442fb678daa862c22d250e
Content-Type: application/json

{
    "name": "Cleaning"
}


###Radera tjänst

DELETE {{baseURL}}/services/63442fb678daa862c22d250e
Content-Type: application/json